- hosts: localhost
  vars_files:
    - defaults/main.yml

  roles: 
    - name: addzone
      NSIP: "{{ NSIP }}"
      zone: "{{ zone }}"

  tasks:
    - name: include main task
      include: tasks/main.yml

  handlers: []
