- name: Init os var
  include_vars: "vars/{{ ansible_system | lower }}.yml"

- set_fact:
    domainname: "{{ host }}.{{ zone }}"
  when: zone != '.'

- set_fact:
    domainname: "{{ host }}."
  when: zone == '.'

- name: Add record
  raw: "echo 'server 127.0.0.1;update add {{ domainname }} 604800 {{ type }} {{ data }};send;quit' | xargs -d \\; -n 1 | nsupdate -k {{ nameddir }}/rndc.key"
  become: true
